### ISSUE TITLE
Error running command: wait: no child processes

### ISSUE THREAD

**Issue by paulbellamy** [tomwilkie/prom-run#2] opened 2016-11-10 18:11 UTC
From the logs
```
2016/11/10 18:08:35 Running '/data/service-conf/infra/terraform_helper' with argments [diff prod]
 - Received signal child exited
 - Grim reaper cleanup: pid=693, wstatus=0
2016/11/10 18:08:38 Error running command: wait: no child processes
 - Grim reaper cleanup: pid=684, wstatus=0
 - Received signal child exited
```

**Comment by tomwilkie** [comment] 2016-11-10 18:13
Whats wrong with this?

**Comment by paulbellamy** [comment] 2016-11-10 18:16
It shouldn't say there is an error when it was successful.

**Comment by tomwilkie** [comment] 2016-11-10 23:59
Caused by this: https://github.com/tomwilkie/prom-run/pull/1

Periodically getting 255s too.

**Comment by tomwilkie** [comment] 2016-11-16 14:52
Fixed in https://github.com/tomwilkie/prom-run/commit/b70ba9aeb14e21b233d8d0b7b75dd43fa749e565

**Closed as completed** 2016-11-16 14:53 UTC
